# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RenderStack_mainWindow.ui'
#
# Created: Mon Oct 24 16:46:15 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_RenderStack_MainWindow(object):
    def setupUi(self, RenderStack_MainWindow):
        RenderStack_MainWindow.setObjectName("RenderStack_MainWindow")
        RenderStack_MainWindow.resize(1078, 1046)
        self.RenderStack_centralwidget = QtGui.QWidget(RenderStack_MainWindow)
        self.RenderStack_centralwidget.setObjectName("RenderStack_centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.RenderStack_centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.renderStack_veticalLayout = QtGui.QVBoxLayout()
        self.renderStack_veticalLayout.setObjectName("renderStack_veticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.update_pushButton = QtGui.QPushButton(self.RenderStack_centralwidget)
        self.update_pushButton.setObjectName("update_pushButton")
        self.horizontalLayout.addWidget(self.update_pushButton)
        self.machineId_label = QtGui.QLabel(self.RenderStack_centralwidget)
        self.machineId_label.setObjectName("machineId_label")
        self.horizontalLayout.addWidget(self.machineId_label)
        self.machineId_lineEdit = QtGui.QLineEdit(self.RenderStack_centralwidget)
        self.machineId_lineEdit.setObjectName("machineId_lineEdit")
        self.horizontalLayout.addWidget(self.machineId_lineEdit)
        self.active_pushButton = QtGui.QPushButton(self.RenderStack_centralwidget)
        self.active_pushButton.setObjectName("active_pushButton")
        self.horizontalLayout.addWidget(self.active_pushButton)
        self.renderStack_veticalLayout.addLayout(self.horizontalLayout)
        self.renderStack_tableWidget = QtGui.QTableWidget(self.RenderStack_centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.renderStack_tableWidget.sizePolicy().hasHeightForWidth())
        self.renderStack_tableWidget.setSizePolicy(sizePolicy)
        self.renderStack_tableWidget.setObjectName("renderStack_tableWidget")
        self.renderStack_tableWidget.setColumnCount(7)
        self.renderStack_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.renderStack_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.renderStack_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.renderStack_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.renderStack_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.renderStack_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.renderStack_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.renderStack_tableWidget.setHorizontalHeaderItem(6, item)
        self.renderStack_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.renderStack_tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.renderStack_tableWidget.horizontalHeader().setStretchLastSection(False)
        self.renderStack_veticalLayout.addWidget(self.renderStack_tableWidget)
        self.action_horizontalLayout = QtGui.QHBoxLayout()
        self.action_horizontalLayout.setObjectName("action_horizontalLayout")
        self.ready2Start_pushButton = QtGui.QPushButton(self.RenderStack_centralwidget)
        self.ready2Start_pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.ready2Start_pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ready2Start_pushButton.setObjectName("ready2Start_pushButton")
        self.action_horizontalLayout.addWidget(self.ready2Start_pushButton)
        self.pushButton = QtGui.QPushButton(self.RenderStack_centralwidget)
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton.setObjectName("pushButton")
        self.action_horizontalLayout.addWidget(self.pushButton)
        self.assingMachine_pushButton = QtGui.QPushButton(self.RenderStack_centralwidget)
        self.assingMachine_pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.assingMachine_pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.assingMachine_pushButton.setObjectName("assingMachine_pushButton")
        self.action_horizontalLayout.addWidget(self.assingMachine_pushButton)
        spacerItem = QtGui.QSpacerItem(40, 50, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.action_horizontalLayout.addItem(spacerItem)
        self.promoteComp_pushButton = QtGui.QPushButton(self.RenderStack_centralwidget)
        self.promoteComp_pushButton.setMinimumSize(QtCore.QSize(0, 80))
        self.promoteComp_pushButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.promoteComp_pushButton.setObjectName("promoteComp_pushButton")
        self.action_horizontalLayout.addWidget(self.promoteComp_pushButton)
        self.renderStack_veticalLayout.addLayout(self.action_horizontalLayout)
        self.verticalLayout.addLayout(self.renderStack_veticalLayout)
        RenderStack_MainWindow.setCentralWidget(self.RenderStack_centralwidget)

        self.retranslateUi(RenderStack_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(RenderStack_MainWindow)

    def retranslateUi(self, RenderStack_MainWindow):
        RenderStack_MainWindow.setWindowTitle(QtGui.QApplication.translate("RenderStack_MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.update_pushButton.setText(QtGui.QApplication.translate("RenderStack_MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.machineId_label.setText(QtGui.QApplication.translate("RenderStack_MainWindow", "Machine Id", None, QtGui.QApplication.UnicodeUTF8))
        self.active_pushButton.setText(QtGui.QApplication.translate("RenderStack_MainWindow", "Active", None, QtGui.QApplication.UnicodeUTF8))
        self.renderStack_tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("RenderStack_MainWindow", "Scene Name", None, QtGui.QApplication.UnicodeUTF8))
        self.renderStack_tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("RenderStack_MainWindow", "Render Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.renderStack_tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("RenderStack_MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.renderStack_tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("RenderStack_MainWindow", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.renderStack_tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("RenderStack_MainWindow", "Render Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.renderStack_tableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("RenderStack_MainWindow", "Machine Status", None, QtGui.QApplication.UnicodeUTF8))
        self.renderStack_tableWidget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("RenderStack_MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.ready2Start_pushButton.setText(QtGui.QApplication.translate("RenderStack_MainWindow", "Set Ready to Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("RenderStack_MainWindow", "Set Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.assingMachine_pushButton.setText(QtGui.QApplication.translate("RenderStack_MainWindow", "Assign Render Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.promoteComp_pushButton.setText(QtGui.QApplication.translate("RenderStack_MainWindow", "Promote to Comp", None, QtGui.QApplication.UnicodeUTF8))

