# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RenderSettings.ui'
#
# Created: Tue Oct 18 16:36:59 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_renderSettings_dockWidget(object):
    def setupUi(self, renderSettings_dockWidget):
        renderSettings_dockWidget.setObjectName("renderSettings_dockWidget")
        renderSettings_dockWidget.resize(293, 890)
        self.renderSettings_Widget = QtGui.QWidget()
        self.renderSettings_Widget.setObjectName("renderSettings_Widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.renderSettings_Widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.setingsLayout = QtGui.QVBoxLayout()
        self.setingsLayout.setObjectName("setingsLayout")
        self.projectPathLabel = QtGui.QLabel(self.renderSettings_Widget)
        self.projectPathLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.projectPathLabel.setObjectName("projectPathLabel")
        self.setingsLayout.addWidget(self.projectPathLabel)
        self.projectPathLineEdit = QtGui.QLineEdit(self.renderSettings_Widget)
        self.projectPathLineEdit.setObjectName("projectPathLineEdit")
        self.setingsLayout.addWidget(self.projectPathLineEdit)
        self.renderEngineLabel = QtGui.QLabel(self.renderSettings_Widget)
        self.renderEngineLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.renderEngineLabel.setObjectName("renderEngineLabel")
        self.setingsLayout.addWidget(self.renderEngineLabel)
        self.renderEngineLineEdit = QtGui.QLineEdit(self.renderSettings_Widget)
        self.renderEngineLineEdit.setObjectName("renderEngineLineEdit")
        self.setingsLayout.addWidget(self.renderEngineLineEdit)
        self.renderFlagsLabel = QtGui.QLabel(self.renderSettings_Widget)
        self.renderFlagsLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.renderFlagsLabel.setObjectName("renderFlagsLabel")
        self.setingsLayout.addWidget(self.renderFlagsLabel)
        self.renderFlagsLineEdit = QtGui.QLineEdit(self.renderSettings_Widget)
        self.renderFlagsLineEdit.setObjectName("renderFlagsLineEdit")
        self.setingsLayout.addWidget(self.renderFlagsLineEdit)
        self.frameRangeLayout = QtGui.QHBoxLayout()
        self.frameRangeLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.frameRangeLayout.setObjectName("frameRangeLayout")
        self.startFrameLabel = QtGui.QLabel(self.renderSettings_Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startFrameLabel.sizePolicy().hasHeightForWidth())
        self.startFrameLabel.setSizePolicy(sizePolicy)
        self.startFrameLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.startFrameLabel.setObjectName("startFrameLabel")
        self.frameRangeLayout.addWidget(self.startFrameLabel)
        self.startFrameSpinBox = QtGui.QSpinBox(self.renderSettings_Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startFrameSpinBox.sizePolicy().hasHeightForWidth())
        self.startFrameSpinBox.setSizePolicy(sizePolicy)
        self.startFrameSpinBox.setObjectName("startFrameSpinBox")
        self.frameRangeLayout.addWidget(self.startFrameSpinBox)
        self.endFrameLabel = QtGui.QLabel(self.renderSettings_Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endFrameLabel.sizePolicy().hasHeightForWidth())
        self.endFrameLabel.setSizePolicy(sizePolicy)
        self.endFrameLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.endFrameLabel.setObjectName("endFrameLabel")
        self.frameRangeLayout.addWidget(self.endFrameLabel)
        self.endFrameSpinBox = QtGui.QSpinBox(self.renderSettings_Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endFrameSpinBox.sizePolicy().hasHeightForWidth())
        self.endFrameSpinBox.setSizePolicy(sizePolicy)
        self.endFrameSpinBox.setObjectName("endFrameSpinBox")
        self.frameRangeLayout.addWidget(self.endFrameSpinBox)
        self.setingsLayout.addLayout(self.frameRangeLayout)
        self.forceCheckBox = QtGui.QCheckBox(self.renderSettings_Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forceCheckBox.sizePolicy().hasHeightForWidth())
        self.forceCheckBox.setSizePolicy(sizePolicy)
        self.forceCheckBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.forceCheckBox.setObjectName("forceCheckBox")
        self.setingsLayout.addWidget(self.forceCheckBox)
        self.setProperties_pushButton = QtGui.QPushButton(self.renderSettings_Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setProperties_pushButton.sizePolicy().hasHeightForWidth())
        self.setProperties_pushButton.setSizePolicy(sizePolicy)
        self.setProperties_pushButton.setMaximumSize(QtCore.QSize(1000, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.setProperties_pushButton.setFont(font)
        self.setProperties_pushButton.setObjectName("setProperties_pushButton")
        self.setingsLayout.addWidget(self.setProperties_pushButton)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.setingsLayout.addItem(spacerItem)
        self.notes_label = QtGui.QLabel(self.renderSettings_Widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.notes_label.setFont(font)
        self.notes_label.setObjectName("notes_label")
        self.setingsLayout.addWidget(self.notes_label)
        self.notes_textBrowser = QtGui.QTextBrowser(self.renderSettings_Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notes_textBrowser.sizePolicy().hasHeightForWidth())
        self.notes_textBrowser.setSizePolicy(sizePolicy)
        self.notes_textBrowser.setObjectName("notes_textBrowser")
        self.setingsLayout.addWidget(self.notes_textBrowser)
        self.replyNote_pushButton = QtGui.QPushButton(self.renderSettings_Widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replyNote_pushButton.sizePolicy().hasHeightForWidth())
        self.replyNote_pushButton.setSizePolicy(sizePolicy)
        self.replyNote_pushButton.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.replyNote_pushButton.setFont(font)
        self.replyNote_pushButton.setObjectName("replyNote_pushButton")
        self.setingsLayout.addWidget(self.replyNote_pushButton)
        self.verticalLayout.addLayout(self.setingsLayout)
        renderSettings_dockWidget.setWidget(self.renderSettings_Widget)

        self.retranslateUi(renderSettings_dockWidget)
        QtCore.QMetaObject.connectSlotsByName(renderSettings_dockWidget)

    def retranslateUi(self, renderSettings_dockWidget):
        renderSettings_dockWidget.setWindowTitle(QtGui.QApplication.translate("renderSettings_dockWidget", "DockWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.projectPathLabel.setText(QtGui.QApplication.translate("renderSettings_dockWidget", "Project Path", None, QtGui.QApplication.UnicodeUTF8))
        self.renderEngineLabel.setText(QtGui.QApplication.translate("renderSettings_dockWidget", "Render Engine", None, QtGui.QApplication.UnicodeUTF8))
        self.renderFlagsLabel.setText(QtGui.QApplication.translate("renderSettings_dockWidget", "render Flags", None, QtGui.QApplication.UnicodeUTF8))
        self.startFrameLabel.setText(QtGui.QApplication.translate("renderSettings_dockWidget", "start Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.endFrameLabel.setText(QtGui.QApplication.translate("renderSettings_dockWidget", "end frame", None, QtGui.QApplication.UnicodeUTF8))
        self.forceCheckBox.setText(QtGui.QApplication.translate("renderSettings_dockWidget", "force by Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.setProperties_pushButton.setText(QtGui.QApplication.translate("renderSettings_dockWidget", "Set Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.notes_label.setText(QtGui.QApplication.translate("renderSettings_dockWidget", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.replyNote_pushButton.setText(QtGui.QApplication.translate("renderSettings_dockWidget", "Reply Note", None, QtGui.QApplication.UnicodeUTF8))

